name: google_vision_flutter
description: Add Google Visions image labeling, face, logo, and landmark detection into your Flutter applications.
version: 1.3.0+3
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision_flutter

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  flutter_image_converter: ^0.3.3
  google_vision: ^1.3.0+2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  grinder: ^0.9.5
  publish_tools: ^1.0.0+4
