name: google_vision_flutter
description: A new Flutter package project.
version: 1.0.0
homepage: https://www.github.com/faithoflifedev/google_vision_flutter

publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  color: ^3.0.0
  google_vision:
    path: ../google_vision
  pcanvas: ^1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  grinder: ^0.9.5
  publish_tools: ^0.1.0+12

  flutter_test:
    sdk: flutter

flutter:
