name: google_vision_flutter
description: Add Google Visions image labeling, face, logo, and landmark detection into your Flutter applications.
version: 1.0.0+1
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision_flutter

# publish_to: "none"

environment:
  sdk: ">=3.2.0 <4.0.0"
  flutter: ">=3.16.0"

dependencies:
  color: ^3.0.0
  google_vision: ^1.1.1+2
  pcanvas: ^1.1.0

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  grinder: ^0.9.5
  publish_tools: ^0.1.0+14

flutter:
