name: google_vision
description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into applications.
version: 1.0.1
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  args: ^2.3.0
  color: ^3.0.0
  crypto_keys: ^0.3.0
  dio: ^4.0.4
  image: ^3.1.0
  jose: ^0.3.2
  json_annotation: ^4.5.0
  retrofit: ^3.0.0
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.1.10
  easy_enum_generator: ^2.0.2
  grinder: ^0.9.1
  json_serializable: ^6.2.0
  lints: ^1.0.1
  retrofit_generator: ^4.0.1
  test: ^1.16.0

executables:
  vision:
