name: google_vision
description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into applications.
version: 1.0.6
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  args: ^2.3.1
  color: ^3.0.0
  crypto_keys: ^0.3.0+1
  dio: ^4.0.6
  image: ^3.2.2
  jose: ^0.3.3
  json_annotation: ^4.8.0
  retrofit: ^3.3.1
  universal_io: ^2.0.4

dev_dependencies:
  build_runner: ^2.3.3
  grinder: ^0.9.2
  json_serializable: ^6.6.1
  lints: ^2.0.0
  publish_tools: ^0.1.0+9
  retrofit_generator: ^4.2.0
  test: ^1.22.0

executables:
  vision:
