name: vision_demo
description: A simple app to test the google_vision_flutter package

publish_to: none

version: 1.0.0+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  color: ^3.0.0
  google_vision_flutter:
    path: ../
  universal_io: ^2.2.2

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/service_credentials.json
    - assets/cn_tower.jpg
    - assets/google_logo.jpg
    - assets/structures.png
    - assets/young-man-smiling.jpg
    - assets/census2010.jpg
    - assets/setagaya_small.jpg
