name: vision_demo
description: A simple app to test the google_vision_flutter package

publish_to: none

version: 1.0.0+2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  color: ^3.0.0
  google_vision_flutter: ^2.0.0
  # google_vision_flutter:
  #   path: ../
  syncfusion_flutter_pdfviewer: ^27.1.50

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/allswell.pdf
    - assets/census2010.jpg
    - assets/cn_tower.jpg
    - assets/dj.jpg # https://commons.wikimedia.org/wiki/Category:Images#/media/File:DJ_Kelblizz.jpg
    - assets/google_logo.jpg
    - assets/service_credentials.json
    - assets/setagaya_small.jpg
    - assets/structures.png
    - assets/young-man-smiling.jpg
