name: google_vision
description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into cross platform applications.
version: 2.0.0+4
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision

topics:
  - api
  - image
  - document

funding:
  - https://www.buymeacoffee.com/faithoflif2

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  args: ^2.6.0
  collection: ^1.18.0
  crypto_keys_plus: ^0.4.0
  dio: ^5.7.0
  flutter_loggy_dio: ^3.1.0
  http: ^1.2.2
  image: ^4.3.0
  jose_plus: ^0.4.6
  json_annotation: ^4.9.0
  loggy: ^2.0.3
  mime: ^2.0.0
  retrofit: ^4.4.1
  universal_platform: ^1.1.0

dev_dependencies:
  build_runner: ^2.4.13
  grinder: ^0.9.5
  json_serializable: ^6.9.0
  lints: ^5.1.0
  publish_tools: ^1.0.0+10
  retrofit_generator: ^9.1.5

executables:
  vision:
