name: google_vision
description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into cross platform applications.
version: 1.2.1
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  args: ^2.5.0
  collection: ^1.18.0
  crypto_keys_plus: ^0.4.0
  dio: ^5.4.3+1
  http: ^1.2.1
  image: ^4.1.7
  jose_plus: ^0.4.6
  json_annotation: ^4.9.0
  retrofit: ^4.1.0
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.9
  grinder: ^0.9.5
  json_serializable: ^6.8.0
  lints: ^4.0.0
  # melos: ^6.0.0
  publish_tools: ^1.0.0+4
  retrofit_generator: ^8.1.0
  test: ^1.25.5

executables:
  vision:
