name: google_vision
description: Allows you to add Google Visions image labeling, face, logo, and landmark detection, OCR, and detection of explicit content, into applications.
version: 1.2.0+2
repository: https://github.com/faithoflifedev/google_vision
homepage: https://github.com/faithoflifedev/google_vision/tree/main/packages/google_vision

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  args: ^2.4.2
  collection: ^1.17.2
  color: ^3.0.0
  crypto_keys_plus: ^0.4.0
  dio: ^5.3.2
  http: ^1.2.0
  image: ^4.1.4
  jose_plus: ^0.4.3
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  universal_io: ^2.2.2

dev_dependencies:
  build_runner: ^2.4.8
  grinder: ^0.9.4
  json_serializable: ^6.7.1
  lints: ^3.0.0
  melos: ^4.1.0
  publish_tools: ^0.1.0+15
  retrofit_generator: ^8.0.6
  test: ^1.25.2

executables:
  vision:
